#!/bin/bash

run_function1 (){

  # remove kernel install from stage2
  sed -i 's/stage2_kernel/#stage2_kernel/g' p2/root/stage2
  
}



run_function2 (){


  mkdir -p /home/${USERNAME}/dev

  DEBEMAIL="cnc@noip.org"
  DEBFULLNAME="cnc"
  export DEBEMAIL DEBFULLNAME

  # dpkg-build tuning flags for rpi4
  CFLAGS="-march=armv8-a+crc+crypto -mtune=cortex-a72"
  echo "APPEND CFLAGS ${CFLAGS}" >> /etc/dpkg/buildflags.conf
  echo "APPEND CXXFLAGS ${CFLAGS}" >> /etc/dpkg/buildflags.conf
  
  # onboard keyboard defaults
  mv -f /root/userscripts/lightdm.conf /etc/lightdm/lightdm.conf
  mv -f /root/userscripts/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf

  # stop lxqt auto notifications at login
  rm /etc/xdg/autostart/lxqt-notifications.desktop



  # install RT kernel
  stage2_kernel



  # LinuxCNC
  echo ""
  echo "Installing LinuxCNC -- 27 July 2022..."
  sleep 1s
  apt install -y linuxcnc-uspace linuxcnc-uspace-dev mesaflash
  dpkg -i /root/userscripts/dpkg/linuxcnc-uspace_*arm64.deb
  dpkg -i /root/userscripts/dpkg/linuxcnc-uspace-dev_*arm64.deb



  # Qtpyvcp
  echo ""
  echo "Installing qtpyvcp ..."
  sleep 1s
  python3 -m pip install /root/userscripts/vtk-*.whl
  cd /home/${USERNAME}/dev
  git clone --depth 1 https://github.com/kcjengr/qtpyvcp
  cd qtpyvcp
  mk-build-deps --install --tool='apt-get -o Debug::pkgProblemResolver=yes --yes' debian/control
  cp scripts/.xsessionrc /home/${USERNAME}/
  chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}
  sudo -u ${USERNAME} python3 -m pip install --editable .
  cp -r linuxcnc /home/${USERNAME}/



  # PyQt5 Designer Plugin
  echo ""
  echo "PyQt5.15.7+dfsg-1 for Qt5.15.4-2-arm64 python3.10"
  mv -f /root/userscripts/dpkg/Qt5.15.4-2-arm64/python3.10/libpyqt5.so \
    /usr/lib/aarch64-linux-gnu/qt5/plugins/designer/libpyqt5.so



  # mesa 22.1.2
  echo ""
  echo "Installing mesa 22.1.2..."
  sleep 1s
  apt install -y freeglut3 libglvnd-dev libglew2.2 libglew-dev libglu1-mesa \
    wayland-protocols libwayland-bin libwayland-dev libclc-13 libclang-cpp14
  dpkg -i /root/userscripts/dpkg/libglapi-mesa_2*arm64.deb
  dpkg -i /root/userscripts/dpkg/libgbm1_2*arm64.deb
  dpkg -i /root/userscripts/dpkg/libgbm-dev_2*arm64.deb
  dpkg -i /root/userscripts/dpkg/libegl-mesa0_2*arm64.deb
  dpkg -i /root/userscripts/dpkg/libegl1-mesa_2*arm64.deb
  dpkg -i /root/userscripts/dpkg/libegl1-mesa-dev_2*arm64.deb
  dpkg -i /root/userscripts/dpkg/libgl1-mesa-dri_2*arm64.deb
  dpkg -i /root/userscripts/dpkg/libglx-mesa0_2*arm64.deb
  dpkg -i /root/userscripts/dpkg/libwayland-egl1-mesa_2*arm64.deb
  dpkg -i /root/userscripts/dpkg/libgl1-mesa-dev_2*arm64.deb
  dpkg -i /root/userscripts/dpkg/mesa-vulkan-drivers_2*arm64.deb
  dpkg -i /root/userscripts/dpkg/mesa-va-drivers_2*arm64.deb
  dpkg -i /root/userscripts/dpkg/mesa-vdpau-drivers_2*arm64.deb
  dpkg -i /root/userscripts/dpkg/mesa-opencl-icd_2*arm64.deb



  # install EtherCAT 1.5.2-33
  dpkg -i /root/userscripts/dpkg/ethercat-dkms_1.5.2-33_all.deb
  dpkg -i /root/userscripts/dpkg/libethercat_1.5.2-33_arm64.deb
  dpkg -i /root/userscripts/dpkg/libethercat-dev_1.5.2-33_arm64.deb
  dpkg -i /root/userscripts/dpkg/ethercat-master_1.5.2-33_arm64.deb
  systemctl enable ethercat.service
  echo 'KERNEL=="EtherCAT[0-9]", MODE="0777"' > /etc/udev/rules.d/99-ethercat.rules



  # LinuxCNC-EtherCAT
  echo ""
  echo "Installing LinuxCNC-EtherCAT..."
  sleep 1s
  cd /home/${USERNAME}/dev
  git clone https://github.com/djsftree/linuxcnc-ethercat.git
  cd linuxcnc-ethercat
  make -j4
  make install
  echo 'KERNEL=="EtherCAT[0-9]", MODE="0777"' > /etc/udev/rules.d/99-ethercat.rules



  # Tidy up
  echo ""
  echo "Tidying up"
  sleep 1s  
  chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}
  apt -y autoremove
  apt -y clean
  apt -y autoclean
}
