#!/usr/bin/env bash

source /root/source.txt
source /root/board.txt
source /root/userdata.txt
export DEBIAN_FRONTEND="noninteractive"

CAP_DISTRO=`echo "$DISTRO" | sed -e "s/\b\(.\)/\u\1/g"`
CAP_RELEASE=`echo "$DISTRO_VERSION" | sed -e "s/\b\(.\)/\u\1/g"`

echo ""
echo -e "\e[1;37mAdding additional packages to $CAP_DISTRO $CAP_RELEASE\e[0m ..."

echo "nameserver ${NAMESERVER1}" > /etc/resolv.conf
echo "nameserver ${NAMESERVER2}" >> /etc/resolv.conf

mount -t proc proc proc/
mount -t sysfs sys sys/

apt-get update
apt-get install -y apt-utils

# Locales
set_locales

# Timezone
set_timezone

apt upgrade -y
apt dist-upgrade -y
if [[ "$DISTRO" == "debian" ]]; then
	apt install -y ${PKGS} ${USER_PKGS} ${SYSMODS} resolvconf openssh-client openssh-server --no-install-recommends;
	apt install -y --no-install-recommends xserver-xorg-video-fbdev;
	apt install -y --no-install-recommends openbox;
	apt install -y --no-install-recommends lightdm;
	apt install -y --no-install-recommends onboard;
	apt install -y --no-install-recommends libmagic-dev libqt5svg5-dev p7zip-full libglib2.0-dev \
    qttools5-dev qttools5-dev-tools libqt5printsupport5 libjson-glib-1.0-0 libxcb-composite0 \
    libxcb-damage0 pulseaudio pipewire-pulse libpulse-mainloop-glib0 libexif-dev libmenu-cache-dev \
    libkf5idletime5 upower;
	apt install -y --no-install-recommends lxqt-core lxqt-branding-debian qt5-style-kvantum-themes;
	apt install -y --no-install-recommends python3-dev python3-wheel python3-pip;
	apt install -y --no-install-recommends dkms equivs devscripts meson ninja-build libdistro-info-perl;
	apt install -y --no-install-recommends network-manager-gnome;
	echo "export QT_STYLE_OVERRIDE=kvantum" >> /etc/environment;
fi
if [[ "$DISTRO" == "devuan" ]]; then
	apt install -y openssh-client openssh-server --no-install-recommends;
	apt install -y ${PKGS} ${USER_PKGS} ${SYSMODS} openresolv;
fi
if [[ "$DISTRO" == "ubuntu" ]]; then
	apt install -y ${PKGS} ${USER_PKGS} ${SYSMODS} openresolv openssh-client openssh-server;
fi
apt -y clean
apt -y autoclean

umount /proc
umount /sys
